version: '3'

services:
  # API
  api:
    container_name: api
    image: promptengineers/llm-server:725c36c
    volumes:
      - ./backend/data:/app/data  # Mount for SQLite database to host directory
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env

  # Proxy (Nginx)
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api

  # Redis (Cache / Broker / Vector Index / Stream)
  redis:
    container_name: redis
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379

  # Ollama (AI Service)
  # ollama:
  #   container_name: ollama
  #   image: ollama/ollama
  #   volumes:
  #     - ./docker/ollama:/ollama  # Mount the directory containing entrypoint.sh
  #   ports:
  #     - 11434:11434
  #   entrypoint: ["/ollama/entrypoint.sh"]  # Specify the entrypoint script
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - capabilities: [gpu]

  # Minio (File Storage) -- CURRENTLY ALL FILES AND IMAGES ARE BASE64 ENCODED
  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: CHANGEME
  #     MINIO_ROOT_PASSWORD: CHANGEME
  #   volumes:
  #     - ~/minio/data:/data
  #     - ~/minio/config:/root/.minio
  #   command: server /data --console-address ":9001"
