name: CI

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      minio:
        image: minio/minio
        ports:
          - 9000:9000
        options: > 
          --name minio
          --env MINIO_ROOT_USER=CHANGEME 
          --env MINIO_ROOT_PASSWORD=CHANGEME
        entrypoint: ["minio", "server", "/data"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ./backend
      run: |
        pip install --upgrade pip
        pip install uv
        uv pip install -v --system --no-cache-dir -c constraints.txt -r requirements.txt

    - name: Run tests
      working-directory: ./backend
      env:
        MINIO_ENDPOINT: http://localhost:9000
        MINIO_ROOT_USER: CHANGEME
        MINIO_ROOT_PASSWORD: CHANGEME
      run: |
        # Assuming your tests are run with pytest
        pytest
